### ISSUE TITLE
palgin hsr exagerated earning after benchmarking

### ISSUE THREAD

**Issue by JhonJhonny** [nemosminer/NemosMiner-v2.3#163]
![palgin](https://user-images.githubusercontent.com/30692674/34771587-560cac20-f605-11e7-8efc-5fd950074ea4.png)
i do not think these numbers from palginhsr are right, before the benchmarks i reset profit too, any clue?
better disabling it for now?

**Comment by HermitHermione** [comment]
Delete _Palgin_NeoScrypt_HashRate.txt_ from **Stats** folder and run benchmark again.
If you still have only 3 1080 Ti's and not ~300 then that's wrong.

**Comment by JhonJhonny** [comment]
ok thaks, i'll try. but what makes you think that i have 3 1080 ti's? Cause i have 3 1080, not ti

**Comment by JhonJhonny** [comment]
Done but.. same thing than before.
![palgin2](https://user-images.githubusercontent.com/30692674/34780831-76757e32-f624-11e7-83ff-9750651daddc.png)
but the thing is that the miner itself is not saying 309mh/s but a total of about 3400 kh/s as u can see?
any other suggestion?

**Comment by HermitHermione** [comment]
Oh remembered wrong about Ti.

Do you use https://github.com/nemosminer/NemosMiner-v2.3/archive/2.3.1+Palgin.zip
That's what I have and it shows correct. I think it's just a decimal typo in the code.
I think there's away to edit something somewhere but I cannot help with that

Just disable for now, GL&HF!

**Comment by JhonJhonny** [comment]
yup i'm using that version, thanks anyway for the help, i'll just disable it for now

**Comment by TomaszDom** [comment]
The hashrate read by nemos is 100x the real value, there is an issue with the decimal point somewhere.

Huge shame as Palgin is faster.

**Comment by TomaszDom** [comment]
@HermitHermione can you attach Wrapper.ps1 or the whole Palgin ZIP archive here? It's no longer available and if that version works fine we can deduce what needs to be changed to fix this issue.

**Comment by TomaszDom** [comment]
Nevermind, I fixed it. Granted, it's an ugly hack, but I cast the decimal hashrate value to an integer just before piping it to the Wrapper text file in Wrapper.ps1 and it now calculates the correct hashrate.

From my very rusty PowerShell knowledge the initial decimal hashrate values are converted to 64-bit floats in the main NemosMiner script anyway and they're stored this way in the stats files, which makes no sense to me, but hey, it works.

**Comment by nemosminer** [comment]
@TomaszDom can attach your Wrapper.ps1 or the whole Palgin ZIP archive here please 

your help would be much appreicated i would like to include PalginHSR-Neoscrypt but have not been able to get it to complete benchmarks yet.. it is definetly faster on 1080ti cards

**Comment by nemosminer** [comment]
fixed thanks for your help

**Comment by TomaszDom** [comment]
@nemosminer are you sure you fixed it? I don't see a fix in the Wrapper code.

**Comment by paskevic** [comment]
problem still there. tested few minutes ago with latest master. palginhsr reports maybe 1000 times better hashrate than actual.

**Comment by roneiv** [comment]
@paskevic I can confirm this, on my rig with 8x1080Ti I experience the same problem. Using the 2.4.1 version which was made available 2 days ago. 

The miner reports overall speed being 12.68MH/s, which seems to lead to an error when calculating the $HashRate  and in the end leading to me getting TH/s benchmarked.

![image](https://user-images.githubusercontent.com/4223807/35323387-90a8fe40-00ed-11e8-924b-a32d5b387207.png)

**Comment by Shotfire** [comment]
This is still a problem for me on 7 GPU's
