### ISSUE TITLE
Please add back -WorkerName switch

### ISSUE THREAD

**Issue by luxferro** [nemosminer/NemosMiner-v2.3#177]
Without it we can't tell our rigs apart or trigger when a worker stops mining.

**Comment by nemosminer** [comment]
its never been removed...

**Comment by luxferro** [comment]
Look here: https://github.com/nemosminer/NemosMiner-v2.3/commit/a5dffab395b938f802bae792c68deaec17524109#diff-91ebc8bc95ec3ed401c6fc1e34af4bff

Then look at the current nicehashstart.bat. Even if I add the -WorkerName switch back to the batch file it doesn't work, so it's function was removed elsewhere as well. Without it, nicehash shows a blank worker name, and I can't trigger alerts if the worker goes down.

**Comment by luxferro** [comment]
If you look at the above commit you'll see it was completely removed. Really the 'ID=' portion should have been removed, as nicehash didn't parse anything after the '=' so your worker name would be 'ID'.

**Comment by nemosminer** [comment]
done : )

**Comment by luxferro** [comment]
I'm afraid it's still broken. I see my worker name now, but it's showing after the -p switch of the command passed to the miner executables, so on nicehash dashboard the worker name is still blank.

edit: Here's a picture: https://i.imgur.com/Vs7b2sH.png
edit2: I think it should look like --user wallet_address.worker_name

**Comment by nemosminer** [comment]
thanks fixed properly this time : )
